### ISSUE TITLE
Implement framework logics for nested elemets validation

### ISSUE THREAD

**Issue by KrukAliaksandr** [AlexGalichenko/cucumber-e2e-po#19]
Implement framework logic for validation of children elements of certain parent elements, that are  in collection by their number range in collection. 
Ex from gherkin: "Some nested elements Aliass" of elements from "1" to "9"  in "Parent Elems Collection Alias" should be visible|clickable etc

**Comment by AlexGalichenko** [comment]
now it's possible to select as ```#1-9 of Collection```

**Comment by AlexGalichenko** [comment]
https://github.com/AlexGalichenko/cucumber-e2e-po/pull/20

**Comment by AlexGalichenko** [comment]
Added in version 0.7.0. Please close if fixed

**Comment by AlexGalichenko** [comment]
#21
